"""
WebSocket routes — real-time clinician alerts and live chat streaming.
"""
from fastapi import APIRouter, WebSocket, WebSocketDisconnect
from services.websocket_manager import WebSocketManager

router = APIRouter()
manager = WebSocketManager()


@router.websocket("/clinician/{clinician_id}")
async def clinician_ws(websocket: WebSocket, clinician_id: str):
    """
    WebSocket endpoint for clinician dashboard.
    Receives: crisis alerts, new lead notifications, session updates.
    """
    await manager.connect(websocket, room=f"clinician:{clinician_id}")
    try:
        while True:
            data = await websocket.receive_text()
            # Clinician can send acknowledgements
            await manager.broadcast_to_room(f"clinician:{clinician_id}", data)
    except WebSocketDisconnect:
        manager.disconnect(websocket, room=f"clinician:{clinician_id}")


@router.websocket("/chat/{session_id}")
async def chat_ws(websocket: WebSocket, session_id: str):
    """
    WebSocket endpoint for streaming AI responses to the widget.
    Streams tokens as they're generated by Qwen 2.5-7B.
    """
    await manager.connect(websocket, room=f"session:{session_id}")
    try:
        while True:
            data = await websocket.receive_text()
            # Forward patient messages for streaming AI response
            await manager.broadcast_to_room(f"session:{session_id}", data)
    except WebSocketDisconnect:
        manager.disconnect(websocket, room=f"session:{session_id}")
